### PR TITLE
Added baseline database to app

### LINKED ISSUE #26: Create Schema for Room Db for weather data storage
Create Classes to define schemas for the current weather and forecast weather tables

### PR DESCRIPTION
**Pull request by Eli-Labell**
Closes #26 

Includes 3 table schema, DAO for each table, and a worker to populate the tables
Requires updated knowledge of what and how the backend is sending over ZMQ

### CODE REVIEW

**Comment by minifigone** [comment]
there's basically a bunch of stuff related to accurately representing the information coming from the NWS API, some of the info is pr #31, other stuff i need to compile together but the general concept is there. i'm not going to approve yet but it looks good once the schema comes in.

**Comment by Eli-Labell** [comment]
> there's basically a bunch of stuff related to accurately representing the information coming from the NWS API, some of the info is pr #31, other stuff i need to compile together but the general concept is there. i'm not going to approve yet but it looks good once the schema comes in.

Yeah. I'm planning on tackling that tomorrow, just wanted to post what I've got before our "remote standup"

**Comment by rbebb** [comment]
Looks good to me, and I'll second what @minifigone said. I'll approve it once what he mentioned is taken care of.

**Comment by Zippoman924** [comment]
Same as both of them for me.

**Review by rbebb — APPROVED** [review]

**Pull request merged**
